# Generated by Django 3.0.7 on 2020-06-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubaccountmodel',
            name='state',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='githubaccountmodel',
            name='access_token',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
