# Generated by Django 3.0.7 on 2020-06-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_githubaccountmodel_git_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=120)),
                ('repo_id', models.CharField(max_length=50)),
                ('git_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='users.GitHubAccountModel')),
            ],
        ),
    ]
