# Generated by Django 3.0.7 on 2020-06-14 07:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=120)),
                ('repo_id', models.CharField(max_length=50)),
                ('hook_id', models.CharField(max_length=40)),
                ('end_sec', models.CharField(max_length=250, unique=True)),
                ('git_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='users.GitHubAccountModel')),
            ],
        ),
        migrations.CreateModel(
            name='WebHookEventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('repo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='repos.RespoModel')),
            ],
        ),
    ]
