# Generated by Django 3.0.7 on 2020-06-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookeventmodel',
            options={'ordering': ['date_time']},
        ),
        migrations.AlterField(
            model_name='webhookeventmodel',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
