# Generated by Django 3.0.7 on 2020-06-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_respomodel_hook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='respomodel',
            name='end_sec',
            field=models.CharField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
