# Generated by Django 3.0.7 on 2020-06-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0004_auto_20200614_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookeventmodel',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
